### PR TITLE
Fixes #224 - Locking api should not swallow exceptions

### LINKED ISSUE #224: Client swallows lightblue errors when trying to acquire lock
If lightblue responds with an error, acquire simply returns false. It should throw an exception.

### PR DESCRIPTION
**Pull request by dcrissman**
See #224

### CODE REVIEW

**Comment by dcrissman** [comment]
@alechenninger - I assume this would resolve your concern.

File: http/src/main/java/com/redhat/lightblue/client/http/LightblueHttpClient.java [hunk 1]
```diff
@@ -206,7 +205,7 @@ public Locking getLocking(String domain) {
      * @see com.redhat.lightblue.client.LightblueClient#metadata(com.redhat.lightblue .client.request.LightblueRequest)
      */
     @Override
-    public DefaultLightblueMetadataResponse metadata(LightblueRequest lightblueRequest) throws LightblueException {
+    public DefaultLightblueMetadataResponse metadata(LightblueRequest lightblueRequest) throws LightblueParseException, LightblueResponseException, LightblueHttpClientException {
```
Comment (paterczm) [inline http/src/main/java/com/redhat/lightblue/client/http/LightblueHttpClient.java]: Why not use LightblueException? In most cases you don't care why it failed.

File: core/src/main/java/com/redhat/lightblue/client/response/DefaultLightblueSingleValueResponse.java [hunk 2]
```diff
@@ -0,0 +1,133 @@
...
+import com.redhat.lightblue.client.util.JSON;
+
+/**
+ * <p>A special response type for responses from lightblue where only a single primitive value is expected.</p>
+ * <p><b>WARNING:</b> There should be only a few special cases where this response type is needed. It is not
+ * recommended for general usage.</p>
+ *
+ * @author dcrissman
+ */
+public class DefaultLightblueSingleValueResponse extends AbstractLightblueResponse implements LightblueResponse, LightblueErrorResponse {
```
Comment (paterczm) [inline core/src/main/java/com/redhat/lightblue/client/response/DefaultLightblueSingleValueResponse.java]: This class contains redundant code. Why not extend DefaultLightblueDataResponse?

File: core/src/main/java/com/redhat/lightblue/client/response/DefaultLightblueDataResponse.java [hunk 3]
```diff
@@ -51,30 +51,6 @@ public boolean hasDataErrors() {
         return err != null && !(err instanceof NullNode) && err.size() > 0;
     }
 
-    @Deprecated
-    @Override
-    public boolean hasError() {
```
Comment (paterczm) [inline core/src/main/java/com/redhat/lightblue/client/response/DefaultLightblueDataResponse.java]: This change is being made long after version bump, a little concerned it will break the build.

File: http/src/main/java/com/redhat/lightblue/client/http/LightblueHttpClient.java (hunk 1 above)
Comment (dcrissman) [inline http/src/main/java/com/redhat/lightblue/client/http/LightblueHttpClient.java]: The client side try/catch block can still catch the generic LightblueException. Why not provide the ability to handle individually if desired?

File: core/src/main/java/com/redhat/lightblue/client/response/DefaultLightblueSingleValueResponse.java (hunk 2 above)
Comment (dcrissman) [inline core/src/main/java/com/redhat/lightblue/client/response/DefaultLightblueSingleValueResponse.java]: Yes, this is duplicate logic. I did this because DefaultLightblueSingleValueResponse is not a LightblueDataResponse. But you are right for the hand slap, let me see if there is a way I can abstract the logic so it is not duplicated.

File: core/src/main/java/com/redhat/lightblue/client/response/DefaultLightblueDataResponse.java (hunk 3 above)
Comment (dcrissman) [inline core/src/main/java/com/redhat/lightblue/client/response/DefaultLightblueDataResponse.java]: We had to break the build already for #230. The major version was bumped in #232.

File: core/src/main/java/com/redhat/lightblue/client/response/DefaultLightblueSingleValueResponse.java (hunk 2 above)
Comment (paterczm) [inline core/src/main/java/com/redhat/lightblue/client/response/DefaultLightblueSingleValueResponse.java]: Maybe just add a new method to get single value from response instead of creating a whole new class?

Comment (dcrissman) [inline core/src/main/java/com/redhat/lightblue/client/response/DefaultLightblueSingleValueResponse.java]: The appropriate exception is LightblueResponseException, and that requires an instance of LightblueErrorResponse.

Comment (dcrissman) [inline core/src/main/java/com/redhat/lightblue/client/response/DefaultLightblueSingleValueResponse.java]: Logic extracted to DefaultLightblueErrorResponse

File: lightblue-client-integration-test/src/test/java/com/redhat/lightblue/client/integration/test/LockingTest.java [hunk 4]
```diff
@@ -32,13 +36,43 @@ public void testAcquireAndRelease() throws Exception {
...
+
+        //assert the lock was successfully released.
+        try {
+            lbLocker.getLockCount("test-lock");
+            fail();
+        } catch (LightblueResponseException e) {
+            Error error = e.getLightblueResponse().getLightblueErrors()[0];
+            assertNotNull(error);
+            assertTrue(error.getMsg().contains("InvalidLockException: test-lock"));
+        }
```
Comment (dcrissman) [inline lightblue-client-integration-test/src/test/java/com/redhat/lightblue/client/integration/test/LockingTest.java]: I mostly just want to highlight this consequence, but here is a case where not swallowing the exception makes for uglier client side code.

Comment (dcrissman) [inline lightblue-client-integration-test/src/test/java/com/redhat/lightblue/client/integration/test/LockingTest.java]: @bserdar - Should a get lock count return an error from lightblue if the resourceId is unknown? Or could it just return 0?

Comment (bserdar) [inline lightblue-client-integration-test/src/test/java/com/redhat/lightblue/client/integration/test/LockingTest.java]: Hm, it is a bit misleading I think, but reasonable. However, the convention
for all the locking APIs is that if the lock is invalid, and a lock becomes
invalid once it is unlocked, they throw exceptions. If it is changed here,
it should be changed in others as well.

One way to deal with ugly code is to create separate lock exceptions for
client, and to make them runtime exceptions.

Comment (bserdar) [inline lightblue-client-integration-test/src/test/java/com/redhat/lightblue/client/integration/test/LockingTest.java]: Lock exceptions are not exactly response exceptions. Maybe you can consider
using a different base exception, something like LockException?

Comment (dcrissman) [inline lightblue-client-integration-test/src/test/java/com/redhat/lightblue/client/integration/test/LockingTest.java]: I think the argument could be made that a lock exception is a response exception. It is just a error on a response from lightblue that happens to be for a lock.

Comment (bserdar) [inline lightblue-client-integration-test/src/test/java/com/redhat/lightblue/client/integration/test/LockingTest.java]: I don't see it that way, but that's just semantics. For sake of clarity, I
think lock exceptions can be thought completely separate from response
errors. That makes client code much cleaner. I don't see any benefit in
extending a common exception for this case. Lock errors don't contain any
diagnostic information.

Comment (dcrissman) [inline lightblue-client-integration-test/src/test/java/com/redhat/lightblue/client/integration/test/LockingTest.java]: Made the changes as discussed, this call is now simplified

**Comment by dcrissman** [comment]
All requested changes should be made at this point. Let me know if you have any feedback.

**Comment by dcrissman** [comment]
I created #247 to sort out on what level data errors should be handled as bulk, metadata, and lock do not have them.

File: core/src/main/java/com/redhat/lightblue/client/response/DefaultLightblueDataResponse.java [hunk 5]
```diff
@@ -157,4 +77,12 @@ public JsonNode getProcessed() {
         }
     }
 
+    protected int parseInt(String fieldName) {
+        JsonNode field = getJson().findValue(fieldName);
+        if (field == null || field.isNull()) {
```
Comment (bserdar) [inline core/src/main/java/com/redhat/lightblue/client/response/DefaultLightblueDataResponse.java]: findValue(x) searches x recursively in the node, or its children. Is this really what you want here? I think you should use get(x).

Comment (dcrissman) [inline core/src/main/java/com/redhat/lightblue/client/response/DefaultLightblueDataResponse.java]: Good catch. fixed.

**Comment by dcrissman** [comment]
Due to the breaking changes introduced, I created https://github.com/lightblue-platform/lightblue-client/pull/253 to bump the major version.
